### ISSUE TITLE
Suggestion to disable check for the productivity modules

### ISSUE THREAD

**Issue by Lippiece** [stevenwdv/rs-base-scanner#1]

**Comment by stevenwdv** [comment]
Hi, thanks for using the mod! You can already do this via the per player mod settings menu. Btw: why do you want to disable it?

**Comment by Lippiece** [comment]
Thanks. I want to disable it because I use the mod in the phases of the game where I don't yet have the modules available.

**Comment by stevenwdv** [comment]
Makes sense. I wanted (want) to add a check for that but I have to go through enabled recipes for that

**Comment by stevenwdv** [comment]
Btw, I improved the behavior in the new version
